services:
  redis:
    image: docker.io/library/redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 15
  hazelcast:
    image: docker.io/hazelcast/hazelcast:5.5
    ports:
      - "5701:5701"
  infinispan:
    image: quay.io/infinispan/server:15.2
    environment:
      USER: admin
      PASS: password
    ports:
      - "11222:11222"
  prometheus:
    image: docker.io/prom/prometheus:v3.5.0
    network_mode: host
    volumes:
      - ./scripts/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  couchbase:
    image: docker.io/couchbase/server:community-7.6.2
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
